-- ─────────────────────────────────────────────────────────────────
-- Migration: 0001_create_workflow_tables  (up)
-- ─────────────────────────────────────────────────────────────────
--
-- Table design
-- ────────────
-- workflows   – one row per diagram (name, description, timestamps)
-- wf_nodes    – one row per node inside a workflow
--               position stored as (x, y) floats
--               type is a TEXT enum: start | process | decision | api | data | end
-- wf_edges    – one row per directed connection between two nodes
--
-- Relationships
--   workflows  1──* wf_nodes   (CASCADE delete)
--   workflows  1──* wf_edges   (CASCADE delete)
--   wf_nodes   is referenced by wf_edges.from_node_id / to_node_id
--
-- All PKs are UUID v4 (generated by the application via the `uuid` crate).
-- ─────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── workflows ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS workflows (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        TEXT        NOT NULL,
    description TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── wf_nodes ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wf_nodes (
    id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    workflow_id UUID        NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    -- The string id used in the React canvas (e.g. "node_1").
    -- Stored so the frontend can restore its local id references.
    canvas_id   TEXT        NOT NULL,
    node_type   TEXT        NOT NULL CHECK (node_type IN ('start','process','decision','api','data','end')),
    label       TEXT        NOT NULL,
    pos_x       FLOAT8      NOT NULL DEFAULT 0,
    pos_y       FLOAT8      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (workflow_id, canvas_id)
);

-- ── wf_edges ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wf_edges (
    id           UUID  PRIMARY KEY DEFAULT uuid_generate_v4(),
    workflow_id  UUID  NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    -- canvas_id for the source node
    from_node_canvas_id TEXT NOT NULL,
    -- canvas_id for the target node
    to_node_canvas_id   TEXT NOT NULL,
    -- Optional user-visible label on the arrow (empty string = no label)
    label        TEXT  NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (workflow_id, from_node_canvas_id, to_node_canvas_id)
);
